[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  'ds-test/=lib/ds-test/src/',
  'solmate/=lib/solmate/src/',
  'splits-contracts/=lib/splits-contracts/contracts/',
]

# ffi = false
# fuzz_runs = 256
# via_ir = true
# optimizer = true
# optimizer_runs = 1000000
# verbosity = 1
# See more config options https://github.com/gakonst/foundry/tree/master/config
